### ISSUE TITLE
Expose byte position in the input stream

### ISSUE THREAD

**Issue by whitequark** [dbuenzli/uutf#1]
This is useful for applications that want to correlate the decoded UTF-8 characters with their position in the original input stream.

**Comment by whitequark** [comment]
Essentially what I want is the byte counterpart to `decoder_count`.

**Comment by dbuenzli** [comment]
Man this patch is going to be ugly.

**Comment by dbuenzli** [comment]
No too ugly in the end. I was looking at the problem from the wrong perspective. Once I realized I always had the info on `ret` it was just a matter of changing that signature, the type system then simply told me were I had to make the changes.

**Comment by whitequark** [comment]
Thank you very much!
