### ISSUE TITLE
New official release needed

### ISSUE THREAD

**Issue by hhugo** [dbuenzli/uutf#12]
to include the bugfix https://github.com/dbuenzli/uutf/commit/f9e3395f04e646b481a35e11e19af66cf9c62f06

**Comment by hhugo** [comment]
cc @trefis

**Comment by hhugo** [comment]
In fact, 1.0.2 is already released but does not appear in this github repo (CHANGES.md, tags, release, ..)

**Comment by dbuenzli** [comment]
Sorry a `git push` went missing. Thanks for the report.
