### ISSUE TITLE
conditionally remove uchar dependency

### ISSUE THREAD

**Issue by sanette** [dbuenzli/uutf#13]
Hello
would it be possible to remove `uchar` dependency by using something like
```
("ocaml" {>= "4.03.0"} | "uchar")
```
in the opam file?

(see https://discuss.ocaml.org/t/compatibility-packages-conditional-dependencies-in-opam/6116)

**Comment by dbuenzli** [comment]
I saw that discussion. My conclusion is that people do like to fuss with build complexity. I don't. 

I don't see what's the problem with that compatibility package, it's empty on >= 4.03.0. 

Like my dependencies on the `result` dependency package which are gradually trimed as releases happen that dependency will naturally disappear when a larger OCaml version gets requested --which will happen at some point. Likely in a year or two.

**Comment by sanette** [comment]
Indeed after installing `uutf`, the directory  `./.opam/4.10.0/lib/uchar` is essentially empty (contains only `META`), and this is thanks to your nice trick in the `build.ml` file. However, the whole source package is still downloaded (in `.opam/4.10.0/.opam-switch/sources/uchar.0.0.2/`).

I'm far from being a specialist of build systems, contrary to you, but don't you think that having a simple check at the level of the build system could be beneficial, by not having to write a specific code for it, and avoiding to download the source when not necessary?

**Comment by dbuenzli** [comment]
> that having a simple check at the level of the build system could be beneficial, by not having to write a specific code for it,

There's precisely nothing to do at the moment in the build system itself, thanks to the compatibility package. 

Frankly I don't have time to waste on what I personally don't see as a problem and something that will anyways disappear by itself in the future. I have around 40ish packages in opam, I can't micromanage non-problems. 

The eco-system moves at it's own pace. Now that debian has 4.05 in stable that's what I usually requires when I do new releases, so when a new release will be done this will likely disappear.

**Comment by sanette** [comment]
I agree that this is a very minor (non)issue for `uutf`, since the size of the whole package to download is small, and as you said it will resolve itself soon. Just for learning, since I had some time to waste, I made some experiments in https://github.com/sanette/uutf. It seems that switching to `dune` gives an easy solution for dealing with conditional dependencies without having to write additional code.
