### ISSUE TITLE
Needs bytes / safe_string support

### ISSUE THREAD

**Issue by whitequark** [dbuenzli/uutf#2]
Only Uutf.Manual.dst should be affected, I think.

**Comment by dbuenzli** [comment]
Didn't look into this yet. But you certainly also want to source from bytes, for zero-copy decoding with `Unix.read`s, so `Uutf.Manual.src` will also be affected. I need to review [this document](https://github.com/dbuenzli/nbcodec/blob/master/RATIONALE.md) with `bytes` in mind.

**Comment by whitequark** [comment]
Ping?

**Comment by dbuenzli** [comment]
Yes.
