### ISSUE TITLE
Allow substring folding

### ISSUE THREAD

**Issue by raphael-proust** [dbuenzli/uutf#4]
I'd like the `String.fold*` functions to take optional arguments for start and length. This is useful because I maintain structures resembling `{content: string; start_bytes: int; start_codes: int; end_bytes: int; end_codes: int;}` and I want to fold over the characters in the range described by `start_*` and `end_*`.

Two questions:
- would a patch be accepted for that?
- would you prefer optional arguments or additional functions with more arguments?

**Comment by dbuenzli** [comment]
Le mercredi, 4 février 2015 à 14:03, Raphaël Proust a écrit :

> Two questions:
> would a patch be accepted for that?

Yes.  

> would you prefer optional arguments or additional functions with more arguments?

Optional arguments seem fine to me, I'd use `pos` and `len` respectively defaulting to `0` and `String.length s`.  

Daniel

**Comment by dbuenzli** [comment]
See  1e7da8d796170284808752b
