### ISSUE TITLE
ocamlfind version: v1.0.0 instead of 1.0.0

### ISSUE THREAD

**Issue by zoggy** [dbuenzli/uutf#9]
Hello,

after installing uutf 1.0.0, ocamlfind reports:
````
$ ocamlfind list | grep uutf
uutf                (version: v1.0.0)
````
It seems to be the same issue as https://github.com/mirage/ocaml-base64/issues/10 for base64.

**Comment by dbuenzli** [comment]
Many of my packages report version with `v` is that a problem for you in practice ?

**Comment by zoggy** [comment]
It was for my scripts checking that required libraries are present in the required version. I fixed my scripts but not in all my libraries (and not in already released libraries), so this may result in configure-time errors.

What's the point of having 'v' ahead a number which is a version number anyway ?
